import {fleetStateText} from './console_stream.js';
import {mountFleet,selectedAircraft,fleetPositions} from './console_fleet.js';
import {mountConnection} from './console_connection.js';
import {receiveBatch,sensorRows} from './console_stream.js';
const $=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';
const stage={takeoff:'이륙',climb:'상승',cruise:'순항',descent:'접근',landing:'수직 착륙',parked:'주기',gate_out:'출발 지상',gate_in:'도착 지상',charge:'회전 준비'};
const states={ready:'Play 대기',starting:'준비 중',preparing:'시작 지점 계산 중',running:'센서 생성 중',waiting:'계획 이륙 대기',paused:'일시정지 · 송신 중단',stopped:'중지 · 송신 중단',landed:'착륙 완료',error:'실행 오류'};
const n=(v,d=1)=>Number.isFinite(v)?v.toFixed(d):'—';
const clock=(v,zone='Asia/Seoul')=>Number.isFinite(v)?new Date(v*1000).toLocaleTimeString('en-GB',{timeZone:zone,hour12:false}):'—';
const date=v=>Number.isFinite(v)?new Date(v*1000).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}):'—';
const clockS=v=>Number.isFinite(v)?`${String(Math.floor(v/3600)%24).padStart(2,'0')}:${String(Math.floor(v/60)%60).padStart(2,'0')}`:'—';
let description,environment,savedEnvironment,catalog=[],selected=null,page=0,preview=null,latest=null,busy=false,catalogVersion=0,previewVersion=0,cursor={process:'',sequence:0,packet:null},tab='operations';
let view={lat:37.53,lon:127.0,scale:1400},mapFit='all';
function message(text,error=false){$('feedback').textContent=text;$('feedback').classList.toggle('error',error);}
async function api(path,options={}){const r=await fetch(path,{cache:'no-store',signal:AbortSignal.timeout(15000),...options});let value;try{value=await r.json();}catch{throw Error('서버 응답을 읽을 수 없습니다.');}if(!r.ok)throw Error(value.message||value.error||`HTTP ${r.status}`);return value;}
function post(path,body){return api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}
function text(tag,value,cls){const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;}
function svg(tag,attrs={},value){const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(value)e.textContent=value;return e;}
function dirty(){previewVersion++;preview=null;$('preview').disabled=false;$('dirty').textContent='변경 초안 · 다음 Play에 적용';$('dirty').classList.add('dirty');$('preview-info').textContent='설정 변경됨 · 경로 미리보기를 눌러 확인';$('map-route').replaceChildren();$('profile').replaceChildren();$('phase-strip').replaceChildren();}
function form(){return {scope:$('execution-scope').value,plan_id:$('plan-source').value,flight_id:selected,time_mode:$('time-mode').value,start_at:$('start-at').value,repeat:$('repeat').checked,seed:Number($('seed').value),terrain:$('terrain').value,flat_height_m:Number($('flat-height').value),environment};}
function timeNote(){const fleet=$('execution-scope').value==='fleet';$('time-mode').querySelector('option[value=plan]').textContent=fleet?'계획 처음부터 · 첫 출발 준비':'계획 처음부터 · 이륙 시각';$('repeat-label').textContent=fleet?' 전체 일정 완료 후 30초 · 반복':' 착륙 후 30초 대기 · 반복';$('scope-note').textContent=fleet?'CSV의 전체 기체·일정과 PSU·버티포트·조종사를 함께 실행합니다.':'선택한 한 기체의 공중 비행과 센서를 시험합니다.';$('selection-note').textContent=fleet?'선택 편은 경로 미리보기':'선택 편만 실행';$('execution-note').textContent=fleet?'전체 운항: PSU·FATO·주기장·지상 이동·회항 준비 포함. 일시정지·중지는 전체 운항에 적용됩니다.':'한 기체 공중 시험: PSU 교통 조율과 지상 운영은 포함하지 않습니다.';const mode=$('time-mode').value;$('start-at-row').hidden=mode!=='at';$('time-note').textContent=fleet?(mode==='now'?'전체 일정의 시작을 지금 시각으로 옮기고 편 간 간격은 유지합니다.':mode==='plan'?'계획의 첫 지상 출발부터 전체 일정을 실행합니다. 센서 UTC는 현재 시각입니다.':'계획 처음부터 지정 시각까지 PSU와 기체 상태를 계산한 뒤 현재 UTC로 송신합니다.') : mode==='now'?'지금 시각에 선택 비행의 이륙을 시작합니다.':mode==='plan'?'계획의 이륙 시각부터 1배속 재생합니다. 센서 UTC는 현재 시각입니다.':'이륙 전이면 출발을 기다리고, 이륙 후이면 해당 경과까지 계산한 뒤 실시간 송신합니다. KST 기준입니다.';}
function chooseFlight(id){selected=id;dirty();renderFlights();const f=catalog.find(x=>x.flight_id===id);if(f){const base=f.date||new Date().toISOString().slice(0,10),sec=f.lift_off_s??f.off_block_s??0;const t=new Date(base+'T00:00:00Z');t.setUTCSeconds(sec);$('start-at').value=t.toISOString().slice(0,19);$('preview-route').textContent=`${f.aircraft_id} · ${f.origin_name||f.origin} → ${f.destination_name||f.destination}`;}void renderPreview();}
function filtered(){const q=$('flight-search').value.trim().toLowerCase();return catalog.filter(f=>[f.flight_id,f.aircraft_id,f.origin,f.destination,f.origin_name,f.destination_name].join(' ').toLowerCase().includes(q));}
function renderFlights(){const rows=filtered(),size=5,pages=Math.max(1,Math.ceil(rows.length/size));page=Math.max(0,Math.min(page,pages-1));$('flight-count').textContent=`${rows.length.toLocaleString()}편 / ${catalog.length.toLocaleString()}편`;$('page-label').textContent=`${page+1} / ${pages}`;$('prev-page').disabled=page===0;$('next-page').disabled=page===pages-1;
  $('flight-list').replaceChildren(...rows.slice(page*size,(page+1)*size).map(f=>{const b=text('button','', 'flight-row');b.setAttribute('role','option');b.setAttribute('aria-selected',String(selected===f.flight_id));b.disabled=Boolean(f.route_error);const top=text('div','');top.append(text('strong',f.aircraft_id+' · '+f.flight_id),text('span',clockS(f.lift_off_s??f.off_block_s),'clock'));b.append(top,text('span',`${f.origin_name||f.origin} → ${f.destination_name||f.destination}`));b.onclick=()=>chooseFlight(f.flight_id);return b;}));if(!rows.length)$('flight-list').append(text('p','검색 결과가 없습니다.','note'));
}
async function loadCatalog(wanted=null){const generation=++catalogVersion;selected=null;preview=null;catalog=[];renderFlights();$('play').disabled=true;message('비행계획을 읽고 있습니다.');
  try{const data=await api('/api/v1/console/catalog/'+encodeURIComponent($('plan-source').value));if(generation!==catalogVersion)return;catalog=data.flights;$('execution-scope').querySelector('option[value=fleet]').disabled=data.kind!=='csv';if(data.kind!=='csv')$('execution-scope').value='single';timeNote();page=0;$('flight-search').value='';const chosen=catalog.find(f=>f.flight_id===wanted&&!f.route_error)||catalog.find(f=>!f.route_error);renderFlights();if(chosen)chooseFlight(chosen.flight_id);else message('해석 가능한 비행이 없습니다.',true);if(data.problems?.length)message('계획 확인: '+data.problems.join(' · '),true);}
  catch(e){if(generation===catalogVersion)message(e.message,true);}finally{if(generation===catalogVersion)$('play').disabled=!selected;}
}
async function loadDescription(preferred=null){description=await api('/api/v1/console');savedEnvironment=structuredClone(description.environment);environment=structuredClone(savedEnvironment);const s=description.settings;$('execution-scope').value=s.scope||'fleet';
  $('plan-source').replaceChildren(...description.plans.map(p=>{const option=text('option',p.name);option.value=p.id;return option;}));$('plan-source').value=preferred||s.plan_id||description.plans[0]?.id||'';
  $('time-mode').value=s.time_mode||'now';$('repeat').checked=s.repeat!==false;$('seed').value=s.seed??42;$('terrain').value=s.terrain||(description.dem_available?'dem':'flat');$('flat-height').value=s.flat_height_m??0;$('flat-row').hidden=$('terrain').value!=='flat';$('terrain').querySelector('option[value=dem]').disabled=!description.dem_available;
  $('dem-info').textContent=description.dem_available?'프로젝트의 원본 DEM·지오이드 패키지를 로컬에서 사용합니다.':'로컬 DEM 없음 · 평탄 환경 또는 해석된 비행 JSON을 사용하세요.';renderPorts();fitMap();timeNote();await loadCatalog(preferred?null:s.flight_id);if(s.start_at){$('start-at').value=s.start_at;void renderPreview();}
}
function renderPorts(){const previous=$('port-select').value;$('port-select').replaceChildren(...environment.vertiports.map(p=>{const o=text('option',p.id+' · '+p.name);o.value=p.id;return o;}));if(environment.vertiports.some(p=>p.id===previous))$('port-select').value=previous;$('port-count').textContent=environment.vertiports.length+'곳';$('environment-name').textContent=environment.name||'가져온 운용 환경';selectPort();}
function selectPort(id){if(id)$('port-select').value=id;const p=environment.vertiports.find(p=>p.id===$('port-select').value);if(!p)return;for(const[k,v]of Object.entries({'port-name':p.name,'port-lat':p.latitude,'port-lon':p.longitude,'port-height':p.platform_height_m,'port-heading':p.heading_deg}))$(k).value=v;$('port-layout').textContent=`주기장 ${p.gates} · FATO ${p.fatos.length} / ${p.pattern}`;drawMap();}
function pointsOfPlan(){return preview?.saved?.phases.flatMap(p=>p.points)||[];}
function fitMap(route=false){mapFit=route?'route':'all';let points=route?pointsOfPlan():[...(environment?.vertiports||[]).map(p=>[p.latitude,p.longitude]),...(environment?.routes?.nodes||[]).map(p=>[p.latitude,p.longitude])];if(!points.length)points=(environment?.vertiports||[]).map(p=>[p.latitude,p.longitude]);if(!points.length)return;const lat=points.map(p=>p[0]),lon=points.map(p=>p[1]);view.lat=(Math.min(...lat)+Math.max(...lat))/2;view.lon=(Math.min(...lon)+Math.max(...lon))/2;view.scale=Math.min(690/Math.max(.015,(Math.max(...lon)-Math.min(...lon))*.793),310/Math.max(.015,Math.max(...lat)-Math.min(...lat)));drawMap();}
function xy(p){return [400+(p[1]-view.lon)*.793*view.scale,205-(p[0]-view.lat)*view.scale];}
function drawMap(){if(!environment)return;const coords=new Map(environment.routes.nodes.map(p=>[p.id,[p.latitude,p.longitude]]));function endpoint(id){return coords.get(id)||(()=>{const p=environment.vertiports.find(p=>String(id).includes(p.id));return p?[p.latitude,p.longitude]:null;})();}
  $('map-lines').replaceChildren(...environment.routes.links.flatMap(l=>{const a=endpoint(l.from),b=endpoint(l.to);if(!a||!b)return[];const[x1,y1]=xy(a),[x2,y2]=xy(b);return [svg('line',{x1,y1,x2,y2,stroke:'#376069','stroke-width':.85,opacity:.7})];}));
  $('map-route').replaceChildren(...(preview?[svg('polyline',{points:pointsOfPlan().map(p=>xy(p).join(',')).join(' '),fill:'none',stroke:'#ebbe81','stroke-width':2.7,'stroke-linecap':'round','stroke-linejoin':'round'})]:[]));
  $('map-ports').replaceChildren(...environment.vertiports.map(p=>{const[x,y]=xy([p.latitude,p.longitude]),g=svg('g',{tabindex:0,role:'button','aria-label':p.name+' 버티포트 정보'}),c=svg('circle',{cx:x,cy:y,r:5,class:'port-dot'+(p.id===$('port-select').value?' selected':'')});g.append(svg('circle',{cx:x,cy:y,r:12,fill:'transparent'}),c,svg('text',{x:x+9,y:y+3,class:'port-label'},p.name));g.onclick=()=>selectPort(p.id);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectPort(p.id);}};return g;}));$('map-scale').textContent=`약 ${n(100/view.scale*111.32,1)} km / 100 px · 위경도 항로도`;drawLive();
}
function drawLive(){const nodes=fleetPositions().map(a=>{const[x,y]=xy([a.latitude_deg,a.longitude_deg]);return svg('circle',{cx:x,cy:y,r:a.airborne?3.5:2.5,fill:a.pilot_failed?'#efa686':a.airborne?'#8fcbe5':'#528688',opacity:.85});});if(latest&&Number.isFinite(latest.latitude_deg)){const[x,y]=xy([latest.latitude_deg,latest.longitude_deg]);nodes.push(svg('circle',{cx:x,cy:y,r:11,fill:'#73e7c320',stroke:'#73e7c340'}),svg('path',{d:'M0 -7 L5 6 L0 3 L-5 6Z',transform:`translate(${x} ${y}) rotate(${latest.heading_deg||0})`,fill:'#90ffe0',stroke:'#c9ffef','stroke-width':1}));}$('map-live').replaceChildren(...nodes);}
function drawProfile(){const points=pointsOfPlan();if(!points.length)return;let distance=0;const values=points.map((p,i)=>{if(i){const prev=points[i-1];distance+=Math.hypot((p[0]-prev[0])*111320,(p[1]-prev[1])*88300);}return [distance,p[2]];});const min=Math.floor(Math.min(...values.map(p=>p[1]))/50)*50,max=Math.max(min+50,Math.ceil(Math.max(...values.map(p=>p[1]))/50)*50),plot=values.map(p=>[48+p[0]/Math.max(1,distance)*730,80-(p[1]-min)/(max-min)*65]);$('profile').replaceChildren(svg('text',{x:3,y:18,fill:'#83a9b4','font-size':10},max+' m'),svg('text',{x:3,y:81,fill:'#83a9b4','font-size':10},min+' m'),svg('path',{d:'M'+plot.map(p=>p.join(' ')).join(' L')+' L778 87 L48 87Z',fill:'#6acab316'}),svg('polyline',{points:plot.map(p=>p.join(',')).join(' '),fill:'none',stroke:'#78cdbc','stroke-width':2}),svg('text',{x:777,y:102,'text-anchor':'end',fill:'#83a9b4','font-size':10},n(distance/1000)+' km · 타원체 고도'));$('phase-strip').replaceChildren(...preview.saved.phases.filter(p=>!['gate_out','gate_in','charge'].includes(p.stage)).map(p=>text('span',stage[p.stage]||p.stage)));}
async function renderPreview(){if(!selected)return;const generation=++previewVersion,input=form();$('preview').disabled=true;message('경로와 지형·착륙 고도를 계산하고 있습니다.');try{const p=await post('/api/v1/console/preview',input);if(generation!==previewVersion)return;preview=p;const f=p.saved.flight;$('preview-route').textContent=`${f.aircraft_id} · ${f.origin_name||f.origin} → ${f.destination_name||f.destination}`;const air=p.saved.phases.filter(x=>!['gate_out','gate_in','charge'].includes(x.stage));$('preview-info').textContent=`${air.length}개 공중 구간 · ${input.terrain==='dem'?'DEM':'평탄 지면'} 기준`;message(p.note+(p.clock.seek_s?` 시작 전 ${n(p.clock.seek_s,0)}초 경과를 계산합니다.`:p.clock.wait_s?` 이륙까지 ${n(p.clock.wait_s,0)}초 대기합니다.`:''));fitMap(true);drawProfile();}catch(e){if(generation===previewVersion)message(e.message,true);}finally{if(generation===previewVersion)$('preview').disabled=false;}}
async function upload(input,kind){const file=input.files[0];if(!file)return;if(file.size>32*1024*1024){message('파일은 32 MB 이하여야 합니다.',true);return;}message('파일을 확인하고 있습니다.');try{const v=await api('/api/v1/console/import?kind='+kind,{method:'POST',headers:{'x-aerodt-filename':encodeURIComponent(file.name)},body:await file.arrayBuffer()});await loadDescription(v.plan_id);message('파일을 가져왔습니다. 미리보기 후 Play로 적용하세요.');}catch(e){message(e.message,true);}finally{input.value='';}}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function control(action){try{await post('/api/v1/control',{action});message({pause:'일시정지 요청 · 기체 진행과 센서 송신을 멈춥니다.',resume:'이어가기 요청 · 새 센서 연속성으로 복구합니다.',stop:'중지 요청 · API와 콘솔은 계속 열려 있습니다.',gnss_outage:'GNSS 10초 누락 시험을 시작합니다.'}[action]||'요청을 보냈습니다.');}catch(e){message(e.message,true);}}
async function refresh(){try{const s=await api('/api/v1/status');paintSensorProfile(s);$('status').textContent=states[s.status]||s.status;$('lamp').classList.toggle('ready',['running','landed','waiting'].includes(s.status));$('aircraft').textContent=s.scope==='fleet'?`${s.fleet?.aircraft??'—'}기체 · 전체 운항`:s.flight.aircraft_id;$('live-route').textContent=s.scope==='fleet'?`${s.fleet?.flights??'—'}편 · 완료 ${s.fleet?.flights_completed??0}편`:`${s.flight.origin_name||s.flight.origin} → ${s.flight.destination_name||s.flight.destination}`;$('aircraft-label').textContent=s.scope==='fleet'?'실행 중 운항 규모':'실행 중 기체';$('gnss-test').textContent=s.scope==='fleet'?'전체 GNSS 10초 누락 시험':'GNSS 10초 누락 시험';$('rate-label').textContent=s.scope==='fleet'?`1× 요청 · 실효 ${n(s.real_time_factor,2)}×`:'1× REAL TIME';$('phase').textContent=s.status==='waiting'?`출발 대기 ${n(s.wait_s,0)}s`:s.status==='preparing'?`준비 ${n((s.seek_progress||0)*100,0)}%`:(s.scope==='fleet'&&s.status==='running'?fleetStateText(s.fleet):stage[s.phase])||states[s.status]||'—';$('elapsed').textContent=(s.scope==='fleet'?'전체 운항 경과 ':'공중 임무 경과 ')+n(s.elapsed_s,1)+' s';$('utc').textContent=clock(s.server_time,'UTC');$('plan-clock').textContent=clock(s.plan_time);$('plan-date').textContent=date(s.plan_time);$('packet-count').textContent=(s.latest_sequence??0).toLocaleString()+' 패킷 · 현재 시각 API 제공';$('run-info').textContent=`${s.mission_id||'Play 대기'} · 계산 지연 ${n((s.lag_s||0)*1000,0)} ms`;
  for(const b of document.querySelectorAll('[data-action=pause]'))b.disabled=!['running','landed','waiting'].includes(s.status);for(const b of document.querySelectorAll('[data-action=resume]'))b.disabled=s.status!=='paused';for(const b of document.querySelectorAll('[data-action=stop]'))b.disabled=['ready','stopped'].includes(s.status);if(s.error)message(s.error,true);
  const requestedAircraft=selectedAircraft();const b=await api(`/api/v1/telemetry?after=${cursor.sequence}&process=${encodeURIComponent(cursor.process)}${requestedAircraft?'&aircraft_id='+encodeURIComponent(requestedAircraft):''}`);if(requestedAircraft!==selectedAircraft())return;const before=cursor;cursor=receiveBatch(cursor,b);const p=cursor.packet;if(!p){latest=null;drawLive();$('packet').textContent='새 센서 패킷 대기 중';}if(p&&cursor!==before){const gnss=p.sensors.gnss?.values;latest=gnss?{latitude_deg:gnss.latitude_deg,longitude_deg:gnss.longitude_deg,heading_deg:p.sensors.ahrs?.values.heading_deg}:null;drawLive();$('packet').textContent=JSON.stringify(p,null,2);} $('sensors').replaceChildren(...sensorRows(cursor.packet,s.server_time).map(v=>{const row=text('tr','');row.classList.toggle('stale',v.age>2);for(const x of[v.id,v.nominal_hz+' Hz',n(v.age,2)+' s'+(v.age>2?' · 지연':''),v.sequence])row.append(text('td',x));return row;}));if(['stopped','ready'].includes(s.status)){latest=null;drawLive();}
}catch(e){$('status').textContent='서버 연결 끊김';$('lamp').classList.remove('ready');}finally{setTimeout(refresh,500);}}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{tab=b.dataset.tab;for(const x of document.querySelectorAll('[data-tab]'))x.classList.toggle('active',x===b);$('operations').hidden=tab!=='operations';$('telemetry').hidden=tab!=='telemetry';$('network').hidden=tab!=='network';$('fleet-view').hidden=tab!=='fleet-view';$('feedback').hidden=['network','fleet-view'].includes(tab);};
$('plan-source').onchange=()=>loadCatalog();$('flight-search').oninput=()=>{page=0;renderFlights();};$('prev-page').onclick=()=>{page--;renderFlights();};$('next-page').onclick=()=>{page++;renderFlights();};$('preview').onclick=renderPreview;
$('play').onclick=async()=>{if(busy||!selected)return;busy=true;$('play').disabled=true;try{const settings=form();await post('/api/v1/console/start',settings);savedEnvironment=structuredClone(environment);$('dirty').textContent='저장 · 실행 적용됨';$('dirty').classList.remove('dirty');message('Play 요청을 반영했습니다. 위쪽 실행 상태에서 준비·송신 상태를 확인하세요.');}catch(e){message(e.message,true);}finally{busy=false;$('play').disabled=!selected;}};
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>control(b.dataset.action);
for(const id of ['execution-scope','time-mode','start-at','repeat','seed','terrain','flat-height'])$(id).onchange=()=>{dirty();timeNote();$('flat-row').hidden=$('terrain').value!=='flat';};
$('port-select').onchange=()=>selectPort();$('edit-port').onclick=()=>{const p=environment.vertiports.find(p=>p.id===$('port-select').value);if(!p)return;const values={'name':$('port-name').value.trim(),'latitude':Number($('port-lat').value),'longitude':Number($('port-lon').value),'platform_height_m':Number($('port-height').value),'heading_deg':Number($('port-heading').value)};if(!values.name||!Number.isFinite(values.latitude)||!Number.isFinite(values.longitude)){message('시설 이름과 좌표를 입력해 주세요.',true);return;}Object.assign(p,values);dirty();renderPorts();message('시설 변경을 초안에 반영했습니다. 미리보기로 경로를 확인하세요.');};
$('plan-file').onchange=()=>upload($('plan-file'),'plan');$('environment-file').onchange=()=>upload($('environment-file'),'environment');$('export-env').onclick=()=>download(environment,'aerodt-physical-environment.json');$('restore-env').onclick=()=>{environment=structuredClone(savedEnvironment);dirty();renderPorts();fitMap();message('마지막 저장 환경으로 되돌렸습니다.');};$('download-plan').onclick=async()=>{try{download(await api('/api/v1/flight-plan'),'aerodt-physical-flight.json');}catch(e){message(e.message,true);}};
$('fit').onclick=()=>fitMap();$('route-fit').onclick=()=>fitMap(true);$('zoom-in').onclick=()=>{view.scale=Math.min(250000,view.scale*1.4);drawMap();};$('zoom-out').onclick=()=>{view.scale=Math.max(100,view.scale/1.4);drawMap();};
let drag=null;$('map').onpointerdown=e=>{if(e.target.closest('[role=button]'))return;drag={x:e.clientX,y:e.clientY,lat:view.lat,lon:view.lon};$('map').setPointerCapture(e.pointerId);};$('map').onpointermove=e=>{if(!drag)return;const factor=800/$('map').getBoundingClientRect().width;view.lat=drag.lat+(e.clientY-drag.y)*factor/view.scale;view.lon=drag.lon-(e.clientX-drag.x)*factor/(view.scale*.793);drawMap();};$('map').onpointerup=()=>drag=null;$('map').onpointercancel=()=>drag=null;
loadDescription().catch(e=>message(e.message,true));refresh();

mountConnection();

mountFleet();
window.addEventListener("physical-aircraft-selected",()=>{cursor={process:"",sequence:0,packet:null};latest=null;$('packet').textContent='선택 기체 센서 수신 대기';$('sensors').replaceChildren();drawLive();});

let sensorProfileDirty=false,sensorProfilePending=false;
$('sensor-profile').onchange=()=>{sensorProfileDirty=true;};
function paintSensorProfile(status){
  const supported=Array.isArray(status.sensor_profiles);
  $('apply-sensor-profile').disabled=!supported||sensorProfilePending;
  $('sensor-profile').disabled=!supported||sensorProfilePending;
  if(!sensorProfileDirty&&!sensorProfilePending)$('sensor-profile').value=status.sensor_profile||'stochastic';
  if(!sensorProfilePending)$('sensor-profile-note').textContent=!supported?'이 기능은 Physical 서버 업데이트 후 사용할 수 있습니다.':
    status.sensor_profile==='known_bias_v1'?'적용 중: 북 +3m · 동 −2m · 고도 +4m · 방위 +2°. 알려진 편향은 Live 수신부에서 제거합니다.':
    '일반 난수 잡음 적용 중. 오차 규칙 변경은 진행 중인 비행을 재시작하지 않습니다.';
}
$('apply-sensor-profile').onclick=async()=>{
  if(sensorProfilePending)return;sensorProfilePending=true;$('apply-sensor-profile').disabled=true;$('sensor-profile').disabled=true;
  try{
    await api('/api/v1/sensor-profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:$('sensor-profile').value})});
    sensorProfileDirty=false;$('sensor-profile-note').textContent='저장했습니다. 다음 센서 관측부터 적용됩니다. 비행은 계속됩니다.';
  }catch(e){$('sensor-profile-note').textContent=e.message;}
  finally{sensorProfilePending=false;$('apply-sensor-profile').disabled=false;$('sensor-profile').disabled=false;}
};
